## 1. 数字的四舍五入

对于简单的舍入运算，使用内置的round(value,ndigits)函数即可

In [1]:
round(1.23,1)

In [2]:
round(1.27,1)

In [3]:
round(-1.27,1)

In [4]:
round(1.25261,3)

1.253

>> 当一个值刚好在两个边界的中间的时候， round 函数返回离它最近的偶数。 也就是说，对1.5或者2.5的舍入运算都会得到2。

传给 round() 函数的 ndigits 参数可以是负数，这种情况下， 舍入运算会作用在十位、百位、千位等上面。比如：

In [5]:
a = 1627731

In [6]:
round(a,-1)

1627730

In [7]:
round(a,-2)

1627700

In [8]:
round(a,-3)

1628000

不要将舍入和格式化输出搞混淆了。 如果你的目的只是简单的输出一定宽度的数，你不需要使用 round() 函数。 而仅仅只需要在格式化的时候指定精度即可。比如：

In [9]:
x = 1.23456

In [10]:
format(x,'.2f')

'1.23'

In [11]:
format(x,'0.3f')

'1.235'

In [12]:
'Value is {:0.3f}'.format(x)

'Value is 1.235'

同样，不要试着去舍入浮点值来”修正”表面上看起来正确的问题。比如，你可能倾向于这样做：

In [13]:
a = 2.1
b = 4.2
c = a + b
c

6.300000000000001

In [14]:
c = round(c,2)

In [15]:
c

6.3

>> 对于大多数使用到浮点的程序，没有必要也不推荐这样做。 尽管在计算的时候会有一点点小的误差，但是这些小的误差是能被理解与容忍的。 如果不能允许这样的小误差(比如涉及到金融领域)，那么就得考虑使用 decimal 模块了，下一节我们会详细讨论。

## 2. 执行i 精确的浮点数运算

In [16]:
a = 2.1
b = 4.2
c = a + b
c

6.300000000000001

In [17]:
(a+b) == 6.3

False

>> 这些错误是由底层CPU和IEEE 754标准通过自己的浮点单位去执行算术时的特征。 由于Python的浮点数据类型使用底层表示存储数据，因此你没办法去避免这样的误差。

In [18]:
# 如果你想更加精确（并且容忍一定的性能损耗），你可以使用decimal模块
from decimal import Decimal

a = Decimal('4.2')
b = Decimal('2.1')
a + b

Decimal('6.3')

In [19]:
print(a+b)

6.3


In [20]:
(a+b) == Decimal('6.3')

True

>> Python新手会倾向于使用 decimal 模块来处理浮点数的精确运算。 然而，先理解你的应用程序目的是非常重要的。 如果你是在做科学计算或工程领域的计算、电脑绘图，或者是科学领域的大多数运算， 那么使用普通的浮点类型是比较普遍的做法。 其中一个原因是，在真实世界中很少会要求精确到普通浮点数能提供的17位精度。 因此，计算过程中的那么一点点的误差是被允许的。 第二点就是，原生的浮点数计算要快的多-有时候你在执行大量运算的时候速度也是非常重要的。

## 3. 数字的格式化输出

解决办法： 内置的format（）函数

In [21]:
x = 1234.56789

In [22]:
# Two decimal places of accuracy
format(x,'0.2f')

'1234.57'

In [23]:
# right justified in 10 chars, one-digit accuracy
format(x,'>10.1f')

'    1234.6'

In [24]:
# left justified
format(x,'<10.1f')

'1234.6    '

In [25]:
# centered 
format(x,'^10.1f')

'  1234.6  '

In [26]:
# inclusion of thousands separator
format(x,',')

'1,234.56789'

In [27]:
format(x,'0,.1f')

'1,234.6'

In [28]:
# 如果你想使用指数记法，将f改成e或者E
format(x,'e')

'1.234568e+03'

In [29]:
format(x,'0.2E')

'1.23E+03'

## 二八十六进制整数

解决办法：bin(),oct(),hex()

In [30]:
x = 1234

In [31]:
bin(x)

'0b10011010010'

In [32]:
oct(x)

'0o2322'

In [33]:
hex(x)

'0x4d2'

另外，如果你不想输出 0b , 0o 或者 0x 的前缀的话，可以使用 format() 函数。比如：

In [34]:
format(x,'b')

'10011010010'

In [35]:
format(x,'o')

'2322'

In [36]:
format(x,'x')

'4d2'

In [37]:
#  整数是有符号的，所以如果你在处理负数的话，输出结果会包含一个负号
x = -1234

In [38]:
format(x,'b')

'-10011010010'

In [39]:
format(x,'x')

'-4d2'

In [40]:
# 为了以不同的进制转换整数字符串，简单的使用带有进制的int()函数即可
int('4d2',16)

1234

In [41]:
int('10011010010',2)

1234

## 5. 字节到大整数的打包与解包

假设你的程序需要处理一个拥有128位长的16个元素的字节字符串。比如：

In [42]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

为了将bytes解析为整数，使用int.from_bytes()方法，并像下面这样指定字节顺序：

In [43]:
len(data)

16

In [44]:
int.from_bytes(data,'little')

69120565665751139577663547927094891008

In [45]:
int.from_bytes(data,'big')

94522842520747284487117727783387188

为了将一个大整数转换为一个字节字符串，使用 int.to_bytes() 方法，并像下面这样指定字节数和字节顺序：

In [46]:
x = 94522842520747284487117727783387188

In [47]:
x.to_bytes(16,'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [48]:
x.to_bytes(16,'little')

b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

## 6. 复数的数学运算

复数可以用使用函数complex(real,imag)或者是带有后缀j的浮点数来指定。

In [49]:
a = complex(2,4)

In [50]:
b = 3 - 5j

In [51]:
a

(2+4j)

In [52]:
b

(3-5j)

In [53]:
a.real

2.0

In [54]:
a.imag

4.0

In [55]:
a.conjugate()

(2-4j)

In [56]:
a + b

(5-1j)

In [57]:
a * b

(26+2j)

In [58]:
a / b

(-0.4117647058823529+0.6470588235294118j)

In [59]:
# 如果要执行其他的复数函数比如正弦、余弦或平方根，使用 cmath 模块：
import cmath

cmath.sin(a)

(24.83130584894638-11.356612711218174j)

In [60]:
cmath.cos(a)

(-11.36423470640106-24.814651485634187j)

In [61]:
cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

## 7. 无穷大与NaN

In [62]:
a = float('inf')

In [63]:
b = float('-inf')

In [64]:
c = float('nan')

In [65]:
a

inf

In [66]:
b

-inf

In [67]:
c

nan

In [68]:
# 为了测试这些值的存在，使用math.isinf()和math.isnan()函数
import math

math.isinf(a)

True

In [69]:
math.isnan(c)

True

In [70]:
# 无穷大数在执行数学计算的时候会传播，比如：
a = float('inf')
a + 45

inf

In [71]:
a * 10

inf

In [72]:
10 / a

0.0

In [73]:
# 但是有些操作时未定义的并返回一个NaN结果。
a = float('inf')
a / a

nan

In [74]:
b = float('-inf')
a + b

nan

In [75]:
# NaN值会在所有操作中传播，而不会产生异常
c = float('nan')
c + 23

nan

In [76]:
c / 2

nan

In [77]:
c * 2

nan

In [78]:
math.sqrt(c)

nan

In [79]:
# NaN值的一个特别的地方是他们之间比较操作总是会返回False
c = float('nan')
d = float('nan')

In [80]:
c == d

False

In [81]:
c is d

False

>> 由于这个原因，测试一个NaN值的唯一安全的方法就是使用math.isnan(),也就是上面掩饰的那样。

## 8. 分数运算

In [82]:
# fractions模块可以被用来执行包含分数的数学运算。
from fractions import Fraction

a = Fraction(5,4)
b = Fraction(7,16)
print(a+b)

27/16


In [83]:
print(a * b)

35/64


In [84]:
# Getting numerator / denomiator
c = a * b
c.numerator

35

In [85]:
c.denominator

64

In [86]:
# Converting to a float
float(c)

0.546875

In [87]:
# Limiting the denominator of a value
print(c.limit_denominator(8))

4/7


## 9. 大型数组运算

涉及到数组的重量级运算操作，可以使用 NumPy 库。 NumPy 的一个主要特征是它会给Python提供一个数组对象，相比标准的Python列表而已更适合用来做数学运算。 下面是一个简单的小例子，向你展示标准列表对象和 NumPy 数组对象之间的差别：



In [88]:
# Python lists
x = [1,2,3,4]
y = [5,6,7,8]

In [89]:
x * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [90]:
x + 10

TypeError: can only concatenate list (not "int") to list

In [91]:
# Numpy arrays
import numpy as np

ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])

In [92]:
ax * 2

array([2, 4, 6, 8])

In [93]:
ax + 10

array([11, 12, 13, 14])

In [94]:
ax + ay

array([ 6,  8, 10, 12])

In [95]:
ax * ay

array([ 5, 12, 21, 32])

>> 正如所见，两种方案中数组的基本数学运算结果并不相同。 特别的， NumPy 中的标量运算(比如 ax * 2 或 ax + 10 )会作用在每一个元素上。 另外，当两个操作数都是数组的时候执行元素对等位置计算，并最终生成一个新的数组。

In [96]:
# Numpy 还未数组提供了大量的通用函数，这些函数可以作为math模块中类似函数的替代。
np.sqrt(ax)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [97]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

>> 使用这些通用函数要比循环数组并使用 math 模块中的函数执行计算要快的多。 因此，只要有可能的话尽量选择 NumPy 的数组方案。

底层实现中， NumPy 数组使用了C或者Fortran语言的机制分配内存。 也就是说，它们是一个非常大的连续的并由同类型数据组成的内存区域。 所以，你可以构造一个比普通Python列表大的多的数组。 比如，如果你想构造一个10,000*10,000的浮点数二维网格，很轻松：

In [98]:
grid = np.zeros(shape=(10000,10000),dtype=float)
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [99]:
# 所有的普通操作还是会同时作用于所有元素上、
grid += 10
grid

array([[10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       ...,
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.]])

In [100]:
np.sin(grid)

array([[-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       ...,
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111]])

>> NumPy 是Python领域中很多科学与工程库的基础，同时也是被广泛使用的最大最复杂的模块。 即便如此，在刚开始的时候通过一些简单的例子和玩具程序也能帮我们完成一些有趣的事情。

>>通常我们导入 NumPy 模块的时候会使用语句 import numpy as np 。 这样的话你就不用再你的程序里面一遍遍的敲入 numpy ，只需要输入 np 就行了，节省了不少时间。

>>如果想获取更多的信息，你当然得去 NumPy 官网逛逛了，网址是： http://www.numpy.org

## 10. 矩阵于线性代数运算

In [101]:
# Numpy库有一个矩阵对象可以用来解决这个问题
import numpy as np

m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [102]:
# Return transpose
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [103]:
# Return inverse
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [104]:
# Create a vector and multipy
v = np.matrix([[2],[3],[4]])
v

matrix([[2],
        [3],
        [4]])

In [105]:
m * v

matrix([[ 8],
        [32],
        [ 2]])

In [106]:
# 可以在numpy.linalg子包中找到更多的操作函数，比如：
import numpy.linalg

# Determinant
numpy.linalg.det(m)

-229.99999999999983

In [107]:
# Eigenvalues
numpy.linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [108]:
# Solve for x in mx = V
x = numpy.linalg.solve(m,v)
x

matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

In [109]:
m * x

matrix([[2.],
        [3.],
        [4.]])

In [110]:
v

matrix([[2],
        [3],
        [4]])

>> 很显然线性代数是个非常大的主题，已经超出了本书能讨论的范围。 但是，如果你需要操作数组和向量的话， NumPy 是一个不错的入口点。 可以访问 NumPy 官网 http://www.numpy.org 获取更多信息。

## 11. 随机选择

random模块有大量的函数用来产生随机数和随机选择元素。比如，要想从一个序列中随机的抽取一个元素，可以使用random.choice()

In [111]:
import random

In [112]:
values = [1,2,3,4,5,6]

In [113]:
random.choice(values)

5

In [114]:
random.choice(values)

6

In [115]:
random.choice(values)

6

In [116]:
random.choice(values)

4

In [117]:
# 为了提取出N个不同的元素的样本用来做进一步的操作，可以使用random.sample()
random.sample(values,2)

[5, 2]

In [118]:
random.sample(values,2)

[3, 2]

In [119]:
# 如果仅仅只是想打乱序列中的元素，可以使用random.shuffle()
random.shuffle(values)

In [120]:
values

[6, 2, 3, 1, 5, 4]

In [121]:
random.shuffle(values)
values

[3, 5, 1, 4, 2, 6]

In [122]:
# 生成随机整数，请使用random.randint()
random.randint(0,10)

3

In [123]:
random.randint(0,10)

10

In [124]:
random.randint(0,10)

3

In [125]:
random.randint(0,10)

10

In [126]:
# 为了生成0到1范围内均匀分布的浮点数，使用random.random()
random.random()

0.7354968181339933

In [127]:
random.random()

0.5199299665742332

In [128]:
random.random()

0.829809527668423

random 模块使用 Mersenne Twister 算法来计算生成随机数。这是一个确定性算法， 但是你可以通过 random.seed() 函数修改初始化种子。比如：

In [129]:
# seed based on system time or os.urandom()
random.seed()

In [130]:
# seed based on interger given
random.seed(12345)

In [131]:
# seed based on byte data
random.seed(b'bytedata')

## 12. 基本的日期与时间转换

为了执行不同时间单位的转换和计算，可以使用datetime模块。比如，为了表示一个时间段，可以创建一个timedelta实例

In [132]:
from datetime import timedelta

In [133]:
a = timedelta(days=2,hours=6)
b = timedelta(hours=4.5)
c = a + b

In [134]:
c.days

2

In [135]:
c.seconds

37800

In [136]:
c.seconds / 3600

10.5

In [137]:
c.total_seconds() / 3600

58.5

In [138]:
# 如果你想表示指定的日期和时间，先创建一个datetime实例，然后使用标准的数学运算来操作它
from datetime import datetime

a = datetime(2012,9,23)

In [139]:
print(a + timedelta(days=10))

2012-10-03 00:00:00


In [140]:
b = datetime(2012,12,21)

In [141]:
d = b - a

In [142]:
d.days

89

In [143]:
now = datetime.today()
print(now)

2019-04-24 23:43:58.409971


In [144]:
print(now + timedelta(minutes= 10))

2019-04-24 23:53:58.409971


In [145]:
# 在计算的时候，需要注意的是datetime会自动调用润年。
a = datetime(2012,3,1)
b = datetime(2012,2,28)
a - b

datetime.timedelta(days=2)

In [146]:
(a - b).days

2

In [147]:
c = datetime(2013,3,1)

In [148]:
d = datetime(2013,2,28)

In [149]:
(c - d).days

1

## 13. 计算最后一个周五的日期

Python的datetime模块中有工具函数和类可以帮助你执行这样的计算

In [150]:
from datetime import datetime,timedelta

weekdays = ['Monday','Tuesday','Wednesday','Thurday','Friday','Saturday','Sunday']

def get_previous_byday(dayname,start_date=None):
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) % 7 
    if days_ago == 0:
        days_ago =7
    target_date = start_date - timedelta(days=days_ago)
    return target_date

In [151]:
datetime.today()

datetime.datetime(2019, 4, 24, 23, 44, 0, 897343)

In [152]:
get_previous_byday("Monday")

datetime.datetime(2019, 4, 22, 23, 44, 1, 111777)

In [153]:
get_previous_byday("Tuesday")

datetime.datetime(2019, 4, 23, 23, 44, 1, 328741)

In [154]:
get_previous_byday("Friday")

datetime.datetime(2019, 4, 19, 23, 44, 1, 583742)

In [155]:
# 可选的start_date参数可以由另外一个datetime实例来提供
get_previous_byday("Sunday",datetime(2012,12,21))

datetime.datetime(2012, 12, 16, 0, 0)

>> 上面的算法原理是这样的：先将开始日期和目标日期映射到星期数组的位置上(星期一索引为0)， 然后通过模运算计算出目标日期要经过多少天才能到达开始日期。然后用开始日期减去那个时间差即得到结果日期。

In [156]:
# 如果你想像这样执行大量的日期计算的话，你最好安装第三方包python-dateutil来代替。
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dateutil.rrule import *
d = datetime.now()
print(d)

2019-04-24 23:44:02.265586


In [157]:
# Next Friday
print(d+relativedelta(weekday=FR))

2019-04-26 23:44:02.265586


In [158]:
# Last Friday
print(d+relativedelta(weekday=FR(-1)))

2019-04-19 23:44:02.265586


## 14. 计算当前月份的日期范围

In [159]:
from datetime import datetime,date,timedelta
import calendar

def get_month_range(start_date=None):
    if start_date is None:
        start_date = date.today().replace(day=1)
    _,days_in_month = calendar.monthrange(start_date.year,start_date.month)
    end_date = start_date + timedelta(days=days_in_month)
    return (start_date,end_date)

In [160]:
# 有了这个就可以很容易的在返回的日期上面做循环操作了
a_day = timedelta(days=1)

In [161]:
first_day,last_day = get_month_range()

In [162]:
while first_day < last_day:
    print(first_day)
    first_day += a_day

2019-04-01
2019-04-02
2019-04-03
2019-04-04
2019-04-05
2019-04-06
2019-04-07
2019-04-08
2019-04-09
2019-04-10
2019-04-11
2019-04-12
2019-04-13
2019-04-14
2019-04-15
2019-04-16
2019-04-17
2019-04-18
2019-04-19
2019-04-20
2019-04-21
2019-04-22
2019-04-23
2019-04-24
2019-04-25
2019-04-26
2019-04-27
2019-04-28
2019-04-29
2019-04-30


## 15. 字符串转换为日期

解决办法：使用Python的标准模块datetime可以很容易的解决这个问题。

In [163]:
from datetime import datetime

In [164]:
text = '2012-09-20'

In [165]:
y = datetime.strptime(text,'%Y-%m-%d')

In [166]:
z = datetime.now()

In [167]:
diff = z - y
diff

datetime.timedelta(days=2407, seconds=85446, microseconds=206129)

>> datetime.strptime() 方法支持很多的格式化代码， 比如 %Y 代表4位数年份， %m 代表两位数月份。 还有一点值得注意的是这些格式化占位符也可以反过来使用，将日期输出为指定的格式字符串形式。

In [168]:
# 假设你的代码中生成了一个datetime对象，你想将它格式化为漂亮易读形式后自动生成的信件
# 中或者报告的顶部。
z

datetime.datetime(2019, 4, 24, 23, 44, 6, 206129)

In [169]:
nice_z = datetime.strftime(z,'%A %B %d, %Y')
nice_z

'Wednesday April 24, 2019'

## 16. 结合时区的日期操作

对几乎所有涉及时区的问题，你都应该使用pytz模块。这个包提供了Olson时区数据库，它是时区信息的事实上的标准，在很多语言和操作系统里面都可以找到。pytz模块一个主要用途是将datetime库创建的简单日期对象本地化

In [170]:
from datetime import datetime
from pytz import timezone
d = datetime(2012,12,21,9,30,0)
print(d)

2012-12-21 09:30:00


In [171]:
# Localize the date for Chicago
central = timezone('US/Central')
loc_d = central.localize(d)
print(loc_d)

2012-12-21 09:30:00-06:00


In [172]:
# convert to Bangalore time
bang_d = loc_d.astimezone(timezone('Asia/Kolkata'))
print(bang_d)

2012-12-21 21:00:00+05:30


如果你打算在本地化日期上执行计算，你需要特别注意夏令时转换和其他细节。 比如，在2013年，美国标准夏令时时间开始于本地时间3月13日凌晨2:00(在那时，时间向前跳过一小时)。 如果你正在执行本地计算，你会得到一个错误。比如：



In [173]:
d = datetime(2013,3,10,1,45)

In [174]:
loc_d = central.localize(d)

In [175]:
print(loc_d)

2013-03-10 01:45:00-06:00


In [176]:
later = loc_d + timedelta(minutes = 30)

In [177]:
print(later) # Wrong!

2013-03-10 02:15:00-06:00


In [178]:
# 上述结果是错误的，为了修正这个问题，可以i 使用时区对象normalize()方法
from datetime import timedelta
later = central.normalize(loc_d + timedelta(minutes = 30))
print(later)

2013-03-10 03:15:00-05:00


In [179]:
# 使用UTC就不需要考虑夏令时相关的问题了。
import pytz
utc_d = loc_d.astimezone(pytz.utc)
print(utc_d)

2013-03-10 07:45:00+00:00


>> 注：当你阅读到这里的时候，有可能 pytz 模块已经不再建议使用了，因为PEP431提出了更先进的时区支持。 但是这里谈到的很多问题还是有参考价值的(比如使用UTC日期的建议等)。